name: run-pytest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: sudo apt install -y python3-pip
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry add -G dev pytest
      - run: poetry add pytest-cov
      - run: poetry update package
      - run: make run-pytest
